"""Seed data for the geo master tables, loaded by migration 0005.

Countries: a standard list of sovereign states (~195). Slugs are derived
from names, not hand-typed, to avoid name/slug mismatches.

India: states/union territories, their districts, and a curated list of
major cities (state capitals + well-known metros) are pre-seeded. This is a
best-effort snapshot, not guaranteed current to the day - Indian district
boundaries change periodically (e.g. Andhra Pradesh's 2022 reorganization).
Anything missing or outdated is correctable via the platform-admin API
afterward (create/update endpoints exist for all four tables) - this is not
a one-shot, uncorrectable data dump.

Every other country's states/districts/cities are intentionally NOT seeded
here - platform admins add them via the API as needed, same as any other
master data.
"""

import re


def _slugify(name: str) -> str:
    slug = re.sub(r'[^a-z0-9]+', '-', name.lower())
    return slug.strip('-')


def _pair(name: str) -> tuple[str, str]:
    return (name, _slugify(name))


def _pairs(names: list[str]) -> list[tuple[str, str]]:
    return [_pair(name) for name in names]


_COUNTRY_NAMES = [
    'Afghanistan',
    'Albania',
    'Algeria',
    'Andorra',
    'Angola',
    'Antigua and Barbuda',
    'Argentina',
    'Armenia',
    'Australia',
    'Austria',
    'Azerbaijan',
    'Bahamas',
    'Bahrain',
    'Bangladesh',
    'Barbados',
    'Belarus',
    'Belgium',
    'Belize',
    'Benin',
    'Bhutan',
    'Bolivia',
    'Bosnia and Herzegovina',
    'Botswana',
    'Brazil',
    'Brunei',
    'Bulgaria',
    'Burkina Faso',
    'Burundi',
    'Cabo Verde',
    'Cambodia',
    'Cameroon',
    'Canada',
    'Central African Republic',
    'Chad',
    'Chile',
    'China',
    'Colombia',
    'Comoros',
    'Congo',
    'Costa Rica',
    'Croatia',
    'Cuba',
    'Cyprus',
    'Czechia',
    'Democratic Republic of the Congo',
    'Denmark',
    'Djibouti',
    'Dominica',
    'Dominican Republic',
    'Ecuador',
    'Egypt',
    'El Salvador',
    'Equatorial Guinea',
    'Eritrea',
    'Estonia',
    'Eswatini',
    'Ethiopia',
    'Fiji',
    'Finland',
    'France',
    'Gabon',
    'Gambia',
    'Georgia',
    'Germany',
    'Ghana',
    'Greece',
    'Grenada',
    'Guatemala',
    'Guinea',
    'Guinea-Bissau',
    'Guyana',
    'Haiti',
    'Honduras',
    'Hungary',
    'Iceland',
    'India',
    'Indonesia',
    'Iran',
    'Iraq',
    'Ireland',
    'Israel',
    'Italy',
    'Jamaica',
    'Japan',
    'Jordan',
    'Kazakhstan',
    'Kenya',
    'Kiribati',
    'Kosovo',
    'Kuwait',
    'Kyrgyzstan',
    'Laos',
    'Latvia',
    'Lebanon',
    'Lesotho',
    'Liberia',
    'Libya',
    'Liechtenstein',
    'Lithuania',
    'Luxembourg',
    'Madagascar',
    'Malawi',
    'Malaysia',
    'Maldives',
    'Mali',
    'Malta',
    'Marshall Islands',
    'Mauritania',
    'Mauritius',
    'Mexico',
    'Micronesia',
    'Moldova',
    'Monaco',
    'Mongolia',
    'Montenegro',
    'Morocco',
    'Mozambique',
    'Myanmar',
    'Namibia',
    'Nauru',
    'Nepal',
    'Netherlands',
    'New Zealand',
    'Nicaragua',
    'Niger',
    'Nigeria',
    'North Korea',
    'North Macedonia',
    'Norway',
    'Oman',
    'Pakistan',
    'Palau',
    'Palestine',
    'Panama',
    'Papua New Guinea',
    'Paraguay',
    'Peru',
    'Philippines',
    'Poland',
    'Portugal',
    'Qatar',
    'Romania',
    'Russia',
    'Rwanda',
    'Saint Kitts and Nevis',
    'Saint Lucia',
    'Saint Vincent and the Grenadines',
    'Samoa',
    'San Marino',
    'Sao Tome and Principe',
    'Saudi Arabia',
    'Senegal',
    'Serbia',
    'Seychelles',
    'Sierra Leone',
    'Singapore',
    'Slovakia',
    'Slovenia',
    'Solomon Islands',
    'Somalia',
    'South Africa',
    'South Korea',
    'South Sudan',
    'Spain',
    'Sri Lanka',
    'Sudan',
    'Suriname',
    'Sweden',
    'Switzerland',
    'Syria',
    'Taiwan',
    'Tajikistan',
    'Tanzania',
    'Thailand',
    'Timor-Leste',
    'Togo',
    'Tonga',
    'Trinidad and Tobago',
    'Tunisia',
    'Turkey',
    'Turkmenistan',
    'Tuvalu',
    'Uganda',
    'Ukraine',
    'United Arab Emirates',
    'United Kingdom',
    'United States',
    'Uruguay',
    'Uzbekistan',
    'Vanuatu',
    'Vatican City',
    'Venezuela',
    'Vietnam',
    'Yemen',
    'Zambia',
    'Zimbabwe',
]

WORLD_COUNTRIES: list[tuple[str, str]] = _pairs(_COUNTRY_NAMES)
INDIA_SLUG = _slugify('India')

_INDIA_STATE_NAMES = [
    'Andhra Pradesh',
    'Arunachal Pradesh',
    'Assam',
    'Bihar',
    'Chhattisgarh',
    'Goa',
    'Gujarat',
    'Haryana',
    'Himachal Pradesh',
    'Jharkhand',
    'Karnataka',
    'Kerala',
    'Madhya Pradesh',
    'Maharashtra',
    'Manipur',
    'Meghalaya',
    'Mizoram',
    'Nagaland',
    'Odisha',
    'Punjab',
    'Rajasthan',
    'Sikkim',
    'Tamil Nadu',
    'Telangana',
    'Tripura',
    'Uttar Pradesh',
    'Uttarakhand',
    'West Bengal',
    # Union territories
    'Andaman and Nicobar Islands',
    'Chandigarh',
    'Dadra and Nagar Haveli and Daman and Diu',
    'Delhi',
    'Jammu and Kashmir',
    'Ladakh',
    'Lakshadweep',
    'Puducherry',
]

INDIA_STATES: list[tuple[str, str]] = _pairs(_INDIA_STATE_NAMES)

_INDIA_DISTRICT_NAMES_BY_STATE: dict[str, list[str]] = {
    'Andhra Pradesh': [
        'Srikakulam',
        'Parvathipuram Manyam',
        'Vizianagaram',
        'Visakhapatnam',
        'Anakapalli',
        'Alluri Sitharama Raju',
        'Kakinada',
        'Konaseema',
        'East Godavari',
        'West Godavari',
        'Eluru',
        'Krishna',
        'NTR',
        'Guntur',
        'Palnadu',
        'Bapatla',
        'Prakasam',
        'Nellore',
        'Kurnool',
        'Nandyal',
        'Anantapur',
        'Sri Sathya Sai',
        'YSR Kadapa',
        'Annamayya',
        'Chittoor',
        'Tirupati',
    ],
    'Arunachal Pradesh': [
        'Tawang',
        'West Kameng',
        'East Kameng',
        'Pakke-Kessang',
        'Papum Pare',
        'Kurung Kumey',
        'Kra Daadi',
        'Lower Subansiri',
        'Upper Subansiri',
        'West Siang',
        'Lower Siang',
        'East Siang',
        'Siang',
        'Upper Siang',
        'Dibang Valley',
        'Lower Dibang Valley',
        'Anjaw',
        'Lohit',
        'Namsai',
        'Changlang',
        'Tirap',
        'Longding',
        'Kamle',
        'Shi Yomi',
        'Leparada',
    ],
    'Assam': [
        'Baksa',
        'Barpeta',
        'Biswanath',
        'Bongaigaon',
        'Cachar',
        'Charaideo',
        'Chirang',
        'Darrang',
        'Dhemaji',
        'Dhubri',
        'Dibrugarh',
        'Dima Hasao',
        'Goalpara',
        'Golaghat',
        'Hailakandi',
        'Hojai',
        'Jorhat',
        'Kamrup',
        'Kamrup Metropolitan',
        'Karbi Anglong',
        'Karimganj',
        'Kokrajhar',
        'Lakhimpur',
        'Majuli',
        'Morigaon',
        'Nagaon',
        'Nalbari',
        'Sivasagar',
        'Sonitpur',
        'South Salmara-Mankachar',
        'Tinsukia',
        'Udalguri',
        'West Karbi Anglong',
        'Bajali',
        'Tamulpur',
    ],
    'Bihar': [
        'Araria',
        'Arwal',
        'Aurangabad',
        'Banka',
        'Begusarai',
        'Bhagalpur',
        'Bhojpur',
        'Buxar',
        'Darbhanga',
        'East Champaran',
        'Gaya',
        'Gopalganj',
        'Jamui',
        'Jehanabad',
        'Kaimur',
        'Katihar',
        'Khagaria',
        'Kishanganj',
        'Lakhisarai',
        'Madhepura',
        'Madhubani',
        'Munger',
        'Muzaffarpur',
        'Nalanda',
        'Nawada',
        'Patna',
        'Purnia',
        'Rohtas',
        'Saharsa',
        'Samastipur',
        'Saran',
        'Sheikhpura',
        'Sheohar',
        'Sitamarhi',
        'Siwan',
        'Supaul',
        'Vaishali',
        'West Champaran',
    ],
    'Chhattisgarh': [
        'Balod',
        'Baloda Bazar',
        'Balrampur',
        'Bastar',
        'Bemetara',
        'Bijapur',
        'Bilaspur',
        'Dantewada',
        'Dhamtari',
        'Durg',
        'Gariaband',
        'Janjgir-Champa',
        'Jashpur',
        'Kabirdham',
        'Kanker',
        'Kondagaon',
        'Korba',
        'Koriya',
        'Mahasamund',
        'Mungeli',
        'Narayanpur',
        'Raigarh',
        'Raipur',
        'Rajnandgaon',
        'Sukma',
        'Surajpur',
        'Surguja',
    ],
    'Goa': ['North Goa', 'South Goa'],
    'Gujarat': [
        'Ahmedabad',
        'Amreli',
        'Anand',
        'Aravalli',
        'Banaskantha',
        'Bharuch',
        'Bhavnagar',
        'Botad',
        'Chhota Udaipur',
        'Dahod',
        'Dang',
        'Devbhoomi Dwarka',
        'Gandhinagar',
        'Gir Somnath',
        'Jamnagar',
        'Junagadh',
        'Kheda',
        'Kutch',
        'Mahisagar',
        'Mehsana',
        'Morbi',
        'Narmada',
        'Navsari',
        'Panchmahal',
        'Patan',
        'Porbandar',
        'Rajkot',
        'Sabarkantha',
        'Surat',
        'Surendranagar',
        'Tapi',
        'Vadodara',
        'Valsad',
    ],
    'Haryana': [
        'Ambala',
        'Bhiwani',
        'Charkhi Dadri',
        'Faridabad',
        'Fatehabad',
        'Gurugram',
        'Hisar',
        'Jhajjar',
        'Jind',
        'Kaithal',
        'Karnal',
        'Kurukshetra',
        'Mahendragarh',
        'Nuh',
        'Palwal',
        'Panchkula',
        'Panipat',
        'Rewari',
        'Rohtak',
        'Sirsa',
        'Sonipat',
        'Yamunanagar',
    ],
    'Himachal Pradesh': [
        'Bilaspur',
        'Chamba',
        'Hamirpur',
        'Kangra',
        'Kinnaur',
        'Kullu',
        'Lahaul and Spiti',
        'Mandi',
        'Shimla',
        'Sirmaur',
        'Solan',
        'Una',
    ],
    'Jharkhand': [
        'Bokaro',
        'Chatra',
        'Deoghar',
        'Dhanbad',
        'Dumka',
        'East Singhbhum',
        'Garhwa',
        'Giridih',
        'Godda',
        'Gumla',
        'Hazaribagh',
        'Jamtara',
        'Khunti',
        'Koderma',
        'Latehar',
        'Lohardaga',
        'Pakur',
        'Palamu',
        'Ramgarh',
        'Ranchi',
        'Sahibganj',
        'Seraikela-Kharsawan',
        'Simdega',
        'West Singhbhum',
    ],
    'Karnataka': [
        'Bagalkot',
        'Ballari',
        'Belagavi',
        'Bengaluru Rural',
        'Bengaluru Urban',
        'Bidar',
        'Chamarajanagar',
        'Chikballapur',
        'Chikkamagaluru',
        'Chitradurga',
        'Dakshina Kannada',
        'Davanagere',
        'Dharwad',
        'Gadag',
        'Hassan',
        'Haveri',
        'Kalaburagi',
        'Kodagu',
        'Kolar',
        'Koppal',
        'Mandya',
        'Mysuru',
        'Raichur',
        'Ramanagara',
        'Shivamogga',
        'Tumakuru',
        'Udupi',
        'Uttara Kannada',
        'Vijayapura',
        'Yadgir',
        'Vijayanagara',
    ],
    'Kerala': [
        'Alappuzha',
        'Ernakulam',
        'Idukki',
        'Kannur',
        'Kasaragod',
        'Kollam',
        'Kottayam',
        'Kozhikode',
        'Malappuram',
        'Palakkad',
        'Pathanamthitta',
        'Thiruvananthapuram',
        'Thrissur',
        'Wayanad',
    ],
    'Madhya Pradesh': [
        'Agar Malwa',
        'Alirajpur',
        'Anuppur',
        'Ashoknagar',
        'Balaghat',
        'Barwani',
        'Betul',
        'Bhind',
        'Bhopal',
        'Burhanpur',
        'Chhatarpur',
        'Chhindwara',
        'Damoh',
        'Datia',
        'Dewas',
        'Dhar',
        'Dindori',
        'Guna',
        'Gwalior',
        'Harda',
        'Narmadapuram',
        'Indore',
        'Jabalpur',
        'Jhabua',
        'Katni',
        'Khandwa',
        'Khargone',
        'Mandla',
        'Mandsaur',
        'Morena',
        'Narsinghpur',
        'Neemuch',
        'Niwari',
        'Panna',
        'Raisen',
        'Rajgarh',
        'Ratlam',
        'Rewa',
        'Sagar',
        'Satna',
        'Sehore',
        'Seoni',
        'Shahdol',
        'Shajapur',
        'Sheopur',
        'Shivpuri',
        'Sidhi',
        'Singrauli',
        'Tikamgarh',
        'Ujjain',
        'Umaria',
        'Vidisha',
    ],
    'Maharashtra': [
        'Ahmednagar',
        'Akola',
        'Amravati',
        'Chhatrapati Sambhajinagar',
        'Beed',
        'Bhandara',
        'Buldhana',
        'Chandrapur',
        'Dhule',
        'Gadchiroli',
        'Gondia',
        'Hingoli',
        'Jalgaon',
        'Jalna',
        'Kolhapur',
        'Latur',
        'Mumbai City',
        'Mumbai Suburban',
        'Nagpur',
        'Nanded',
        'Nandurbar',
        'Nashik',
        'Dharashiv',
        'Palghar',
        'Parbhani',
        'Pune',
        'Raigad',
        'Ratnagiri',
        'Sangli',
        'Satara',
        'Sindhudurg',
        'Solapur',
        'Thane',
        'Wardha',
        'Washim',
        'Yavatmal',
    ],
    'Manipur': [
        'Bishnupur',
        'Chandel',
        'Churachandpur',
        'Imphal East',
        'Imphal West',
        'Jiribam',
        'Kakching',
        'Kamjong',
        'Kangpokpi',
        'Noney',
        'Pherzawl',
        'Senapati',
        'Tamenglong',
        'Tengnoupal',
        'Thoubal',
        'Ukhrul',
    ],
    'Meghalaya': [
        'East Garo Hills',
        'East Jaintia Hills',
        'East Khasi Hills',
        'Eastern West Khasi Hills',
        'North Garo Hills',
        'Ri Bhoi',
        'South Garo Hills',
        'South West Garo Hills',
        'South West Khasi Hills',
        'West Garo Hills',
        'West Jaintia Hills',
        'West Khasi Hills',
    ],
    'Mizoram': [
        'Aizawl',
        'Champhai',
        'Hnahthial',
        'Khawzawl',
        'Kolasib',
        'Lawngtlai',
        'Lunglei',
        'Mamit',
        'Saiha',
        'Saitual',
        'Serchhip',
    ],
    'Nagaland': [
        'Chumoukedima',
        'Dimapur',
        'Kiphire',
        'Kohima',
        'Longleng',
        'Mokokchung',
        'Mon',
        'Niuland',
        'Noklak',
        'Peren',
        'Phek',
        'Shamator',
        'Tseminyu',
        'Tuensang',
        'Wokha',
        'Zunheboto',
    ],
    'Odisha': [
        'Angul',
        'Balangir',
        'Balasore',
        'Bargarh',
        'Bhadrak',
        'Boudh',
        'Cuttack',
        'Deogarh',
        'Dhenkanal',
        'Gajapati',
        'Ganjam',
        'Jagatsinghpur',
        'Jajpur',
        'Jharsuguda',
        'Kalahandi',
        'Kandhamal',
        'Kendrapara',
        'Kendujhar',
        'Khordha',
        'Koraput',
        'Malkangiri',
        'Mayurbhanj',
        'Nabarangpur',
        'Nayagarh',
        'Nuapada',
        'Puri',
        'Rayagada',
        'Sambalpur',
        'Subarnapur',
        'Sundargarh',
    ],
    'Punjab': [
        'Amritsar',
        'Barnala',
        'Bathinda',
        'Faridkot',
        'Fatehgarh Sahib',
        'Fazilka',
        'Ferozepur',
        'Gurdaspur',
        'Hoshiarpur',
        'Jalandhar',
        'Kapurthala',
        'Ludhiana',
        'Malerkotla',
        'Mansa',
        'Moga',
        'Muktsar',
        'Pathankot',
        'Patiala',
        'Rupnagar',
        'Sahibzada Ajit Singh Nagar',
        'Sangrur',
        'Shahid Bhagat Singh Nagar',
        'Tarn Taran',
    ],
    'Rajasthan': [
        'Ajmer',
        'Alwar',
        'Banswara',
        'Baran',
        'Barmer',
        'Bharatpur',
        'Bhilwara',
        'Bikaner',
        'Bundi',
        'Chittorgarh',
        'Churu',
        'Dausa',
        'Dholpur',
        'Dungarpur',
        'Hanumangarh',
        'Jaipur',
        'Jaisalmer',
        'Jalore',
        'Jhalawar',
        'Jhunjhunu',
        'Jodhpur',
        'Karauli',
        'Kota',
        'Nagaur',
        'Pali',
        'Pratapgarh',
        'Rajsamand',
        'Sawai Madhopur',
        'Sikar',
        'Sirohi',
        'Sri Ganganagar',
        'Tonk',
        'Udaipur',
    ],
    'Sikkim': ['Gangtok', 'Gyalshing', 'Mangan', 'Namchi', 'Pakyong', 'Soreng'],
    'Tamil Nadu': [
        'Ariyalur',
        'Chengalpattu',
        'Chennai',
        'Coimbatore',
        'Cuddalore',
        'Dharmapuri',
        'Dindigul',
        'Erode',
        'Kallakurichi',
        'Kanchipuram',
        'Kanyakumari',
        'Karur',
        'Krishnagiri',
        'Madurai',
        'Mayiladuthurai',
        'Nagapattinam',
        'Namakkal',
        'Nilgiris',
        'Perambalur',
        'Pudukkottai',
        'Ramanathapuram',
        'Ranipet',
        'Salem',
        'Sivaganga',
        'Tenkasi',
        'Thanjavur',
        'Theni',
        'Thoothukudi',
        'Tiruchirappalli',
        'Tirunelveli',
        'Tirupathur',
        'Tiruppur',
        'Tiruvallur',
        'Tiruvannamalai',
        'Tiruvarur',
        'Vellore',
        'Viluppuram',
        'Virudhunagar',
    ],
    'Telangana': [
        'Adilabad',
        'Bhadradri Kothagudem',
        'Hyderabad',
        'Jagtial',
        'Jangaon',
        'Jayashankar Bhupalpally',
        'Jogulamba Gadwal',
        'Kamareddy',
        'Karimnagar',
        'Khammam',
        'Kumuram Bheem',
        'Mahabubabad',
        'Mahabubnagar',
        'Mancherial',
        'Medak',
        'Medchal-Malkajgiri',
        'Mulugu',
        'Nagarkurnool',
        'Nalgonda',
        'Narayanpet',
        'Nirmal',
        'Nizamabad',
        'Peddapalli',
        'Rajanna Sircilla',
        'Rangareddy',
        'Sangareddy',
        'Siddipet',
        'Suryapet',
        'Vikarabad',
        'Wanaparthy',
        'Warangal',
        'Hanumakonda',
        'Yadadri Bhuvanagiri',
    ],
    'Tripura': [
        'Dhalai',
        'Gomati',
        'Khowai',
        'North Tripura',
        'Sepahijala',
        'South Tripura',
        'Unakoti',
        'West Tripura',
    ],
    'Uttar Pradesh': [
        'Agra',
        'Aligarh',
        'Ambedkar Nagar',
        'Amethi',
        'Amroha',
        'Auraiya',
        'Ayodhya',
        'Azamgarh',
        'Baghpat',
        'Bahraich',
        'Ballia',
        'Balrampur',
        'Banda',
        'Barabanki',
        'Bareilly',
        'Basti',
        'Bhadohi',
        'Bijnor',
        'Budaun',
        'Bulandshahr',
        'Chandauli',
        'Chitrakoot',
        'Deoria',
        'Etah',
        'Etawah',
        'Farrukhabad',
        'Fatehpur',
        'Firozabad',
        'Gautam Buddha Nagar',
        'Ghaziabad',
        'Ghazipur',
        'Gonda',
        'Gorakhpur',
        'Hamirpur',
        'Hapur',
        'Hardoi',
        'Hathras',
        'Jalaun',
        'Jaunpur',
        'Jhansi',
        'Kannauj',
        'Kanpur Dehat',
        'Kanpur Nagar',
        'Kasganj',
        'Kaushambi',
        'Kheri',
        'Kushinagar',
        'Lalitpur',
        'Lucknow',
        'Maharajganj',
        'Mahoba',
        'Mainpuri',
        'Mathura',
        'Mau',
        'Meerut',
        'Mirzapur',
        'Moradabad',
        'Muzaffarnagar',
        'Pilibhit',
        'Pratapgarh',
        'Prayagraj',
        'Rae Bareli',
        'Rampur',
        'Saharanpur',
        'Sambhal',
        'Sant Kabir Nagar',
        'Shahjahanpur',
        'Shamli',
        'Shravasti',
        'Siddharthnagar',
        'Sitapur',
        'Sonbhadra',
        'Sultanpur',
        'Unnao',
        'Varanasi',
    ],
    'Uttarakhand': [
        'Almora',
        'Bageshwar',
        'Chamoli',
        'Champawat',
        'Dehradun',
        'Haridwar',
        'Nainital',
        'Pauri Garhwal',
        'Pithoragarh',
        'Rudraprayag',
        'Tehri Garhwal',
        'Udham Singh Nagar',
        'Uttarkashi',
    ],
    'West Bengal': [
        'Alipurduar',
        'Bankura',
        'Birbhum',
        'Cooch Behar',
        'Dakshin Dinajpur',
        'Darjeeling',
        'Hooghly',
        'Howrah',
        'Jalpaiguri',
        'Jhargram',
        'Kalimpong',
        'Kolkata',
        'Malda',
        'Murshidabad',
        'Nadia',
        'North 24 Parganas',
        'Paschim Bardhaman',
        'Paschim Medinipur',
        'Purba Bardhaman',
        'Purba Medinipur',
        'Purulia',
        'South 24 Parganas',
        'Uttar Dinajpur',
    ],
    # Union territories
    'Andaman and Nicobar Islands': [
        'Nicobar',
        'North and Middle Andaman',
        'South Andaman',
    ],
    'Chandigarh': ['Chandigarh'],
    'Dadra and Nagar Haveli and Daman and Diu': [
        'Dadra and Nagar Haveli',
        'Daman',
        'Diu',
    ],
    'Delhi': [
        'Central Delhi',
        'East Delhi',
        'New Delhi',
        'North Delhi',
        'North East Delhi',
        'North West Delhi',
        'Shahdara',
        'South Delhi',
        'South East Delhi',
        'South West Delhi',
        'West Delhi',
    ],
    'Jammu and Kashmir': [
        'Anantnag',
        'Bandipora',
        'Baramulla',
        'Budgam',
        'Doda',
        'Ganderbal',
        'Jammu',
        'Kathua',
        'Kishtwar',
        'Kulgam',
        'Kupwara',
        'Poonch',
        'Pulwama',
        'Rajouri',
        'Ramban',
        'Reasi',
        'Samba',
        'Shopian',
        'Srinagar',
        'Udhampur',
    ],
    'Ladakh': ['Kargil', 'Leh'],
    'Lakshadweep': ['Lakshadweep'],
    'Puducherry': ['Karaikal', 'Mahe', 'Puducherry', 'Yanam'],
}

INDIA_DISTRICTS_BY_STATE: dict[str, list[tuple[str, str]]] = {
    _slugify(state_name): _pairs(district_names)
    for state_name, district_names in _INDIA_DISTRICT_NAMES_BY_STATE.items()
}

# (city name, state name, district name or None) - curated state capitals +
# well-known metros only, not exhaustive. district is filled in only where
# the city shares its name with one of the districts listed above.
_INDIA_MAJOR_CITIES = [
    ('Amaravati', 'Andhra Pradesh', None),
    ('Visakhapatnam', 'Andhra Pradesh', 'Visakhapatnam'),
    ('Vijayawada', 'Andhra Pradesh', 'NTR'),
    ('Guntur', 'Andhra Pradesh', 'Guntur'),
    ('Nellore', 'Andhra Pradesh', 'Nellore'),
    ('Itanagar', 'Arunachal Pradesh', None),
    ('Guwahati', 'Assam', 'Kamrup Metropolitan'),
    ('Patna', 'Bihar', 'Patna'),
    ('Gaya', 'Bihar', 'Gaya'),
    ('Raipur', 'Chhattisgarh', 'Raipur'),
    ('Bilaspur', 'Chhattisgarh', 'Bilaspur'),
    ('Panaji', 'Goa', 'North Goa'),
    ('Ahmedabad', 'Gujarat', 'Ahmedabad'),
    ('Surat', 'Gujarat', 'Surat'),
    ('Vadodara', 'Gujarat', 'Vadodara'),
    ('Gandhinagar', 'Gujarat', 'Gandhinagar'),
    ('Gurugram', 'Haryana', 'Gurugram'),
    ('Faridabad', 'Haryana', 'Faridabad'),
    ('Shimla', 'Himachal Pradesh', 'Shimla'),
    ('Ranchi', 'Jharkhand', 'Ranchi'),
    ('Jamshedpur', 'Jharkhand', 'East Singhbhum'),
    ('Dhanbad', 'Jharkhand', 'Dhanbad'),
    ('Bengaluru', 'Karnataka', 'Bengaluru Urban'),
    ('Mysuru', 'Karnataka', 'Mysuru'),
    ('Hubballi', 'Karnataka', None),
    ('Thiruvananthapuram', 'Kerala', 'Thiruvananthapuram'),
    ('Kochi', 'Kerala', 'Ernakulam'),
    ('Kozhikode', 'Kerala', 'Kozhikode'),
    ('Bhopal', 'Madhya Pradesh', 'Bhopal'),
    ('Indore', 'Madhya Pradesh', 'Indore'),
    ('Jabalpur', 'Madhya Pradesh', 'Jabalpur'),
    ('Mumbai', 'Maharashtra', 'Mumbai City'),
    ('Pune', 'Maharashtra', 'Pune'),
    ('Nagpur', 'Maharashtra', 'Nagpur'),
    ('Imphal', 'Manipur', 'Imphal West'),
    ('Shillong', 'Meghalaya', 'East Khasi Hills'),
    ('Aizawl', 'Mizoram', 'Aizawl'),
    ('Kohima', 'Nagaland', 'Kohima'),
    ('Dimapur', 'Nagaland', 'Dimapur'),
    ('Bhubaneswar', 'Odisha', None),
    ('Cuttack', 'Odisha', 'Cuttack'),
    ('Chandigarh', 'Punjab', None),
    ('Ludhiana', 'Punjab', 'Ludhiana'),
    ('Amritsar', 'Punjab', 'Amritsar'),
    ('Jaipur', 'Rajasthan', 'Jaipur'),
    ('Jodhpur', 'Rajasthan', 'Jodhpur'),
    ('Udaipur', 'Rajasthan', 'Udaipur'),
    ('Gangtok', 'Sikkim', 'Gangtok'),
    ('Chennai', 'Tamil Nadu', 'Chennai'),
    ('Coimbatore', 'Tamil Nadu', 'Coimbatore'),
    ('Madurai', 'Tamil Nadu', 'Madurai'),
    ('Hyderabad', 'Telangana', 'Hyderabad'),
    ('Agartala', 'Tripura', None),
    ('Lucknow', 'Uttar Pradesh', 'Lucknow'),
    ('Kanpur', 'Uttar Pradesh', 'Kanpur Nagar'),
    ('Varanasi', 'Uttar Pradesh', 'Varanasi'),
    ('Agra', 'Uttar Pradesh', 'Agra'),
    ('Dehradun', 'Uttarakhand', 'Dehradun'),
    ('Kolkata', 'West Bengal', 'Kolkata'),
    ('Howrah', 'West Bengal', 'Howrah'),
    ('Port Blair', 'Andaman and Nicobar Islands', 'South Andaman'),
    ('Chandigarh', 'Chandigarh', 'Chandigarh'),
    ('Silvassa', 'Dadra and Nagar Haveli and Daman and Diu', 'Dadra and Nagar Haveli'),
    ('Daman', 'Dadra and Nagar Haveli and Daman and Diu', 'Daman'),
    ('New Delhi', 'Delhi', 'New Delhi'),
    ('Srinagar', 'Jammu and Kashmir', 'Srinagar'),
    ('Jammu', 'Jammu and Kashmir', 'Jammu'),
    ('Leh', 'Ladakh', 'Leh'),
    ('Kavaratti', 'Lakshadweep', 'Lakshadweep'),
    ('Puducherry', 'Puducherry', 'Puducherry'),
]

# (city_name, city_slug, state_slug, district_slug_or_None)
# City uniqueness is scoped per-state (see the schema), so a plain slugify
# of the city name alone is sufficient - no two entries here share both the
# same state and the same city name.
INDIA_MAJOR_CITIES: list[tuple[str, str, str, str | None]] = [
    (
        city_name,
        _slugify(city_name),
        _slugify(state_name),
        _slugify(district_name) if district_name is not None else None,
    )
    for city_name, state_name, district_name in _INDIA_MAJOR_CITIES
]
